name: pip - List outdated

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * 1'

jobs:
  outdated:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install and check for outdated
        run: |
          pip install -r requirements.txt
          pip list --outdated
